# Generated by Django 5.0.3 on 2024-03-21 02:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment_education_experience_rating_reply_share_like_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='name',
            new_name='social',
        ),
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(blank=True, null=True, related_name='contributed_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
