# Generated by Django 4.2.7 on 2024-03-30 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_project_contributors"),
    ]

    operations = [
        migrations.RemoveField(model_name="userdetails", name="resume",),
    ]
