# Generated by Django 5.0.3 on 2024-03-29 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_userdetails_options_userdetails_unique_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='education',
            unique_together={('user', 'institute')},
        ),
        migrations.AlterUniqueTogether(
            name='experience',
            unique_together={('user', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('user', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='social',
            unique_together={('user', 'social')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('user', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='tool',
            unique_together={('user', 'tool')},
        ),
    ]
