# Generated by Django 5.0.3 on 2024-03-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_social_unique_together_userdetails_socials_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='education',
            unique_together={('institute',)},
        ),
        migrations.AlterUniqueTogether(
            name='experience',
            unique_together={('company',)},
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('skill',)},
        ),
        migrations.AddField(
            model_name='userdetails',
            name='educations',
            field=models.ManyToManyField(blank=True, related_name='education', to='api.education'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='experiences',
            field=models.ManyToManyField(blank=True, related_name='experience', to='api.experience'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='skills', to='api.skill'),
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
    ]
