# Generated by Django 5.0.3 on 2024-04-01 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_education_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='resume',
        ),
    ]
