# Generated by Django 4.2.7 on 2024-04-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_education_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
    ]
