# Generated by Django 4.2.7 on 2024-04-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_post_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project", name="video", field=models.URLField(blank=True),
        ),
    ]
