# Generated by Django 4.2.7 on 2024-03-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_posttags_tags_posttags_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttags',
            name='name',
        ),
        migrations.AlterField(
            model_name='posttags',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
