# Generated by Django 4.2.7 on 2024-03-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_remove_posttags_name_alter_posttags_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttags',
            old_name='tags',
            new_name='name',
        ),
    ]
