# Generated by Django 4.2.7 on 2024-03-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0018_alter_social_icon_alter_social_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='static/icons/'),
        ),
    ]
